---
clients:
  browser:
    registration:
      client-id: browser
      # yamllint disable-line rule:quoted-strings
      client-secret: "${TM_BROWSER_CLIENT_SECRET}"
      client-name: Taskmigo browser client
      client-authentication-methods:
        - client_secret_basic
      authorization-grant-types:
        - authorization_code
        - refresh_token
      redirect-uris:
        # yamllint disable-line rule:quoted-strings
        - "${TM_BROWSER_HOST_NAME:http://localhost}/api/auth/callback"
      post-logout-redirect-uris:
        # yamllint disable-line rule:quoted-strings
        - "${TM_BROWSER_HOST_NAME:http://localhost}/"
      scopes:
        - openid
        - profile
    require-proof-key: true
    require-authorization-consent: false
    token:
      access-token-time-to-live: PT5M
      refresh-token-time-to-live: PT8H
      reuse-refresh-tokens: false
