spring:
  datasource:
    url: ${TASKMIGO_DATABASE_URL:jdbc:postgresql://localhost:5432/taskmigo}
    username: ${TASKMIGO_DATABASE_USERNAME:taskmigo}
    password: ${TASKMIGO_DATABASE_PASSWORD:taskmigo}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    validate-migration-naming: true
