---
clients:
  browser:
    registration:
      client-id: taskmigo-client
      client-secret: "${TASKMIGO_AUTH_CLIENT_SECRET_HASH}"  # yamllint disable-line rule:quoted-strings
      client-name: Taskmigo browser client
      client-authentication-methods:
        - client_secret_basic
      authorization-grant-types:
        - authorization_code
        - refresh_token
      redirect-uris:
        - "${TASKMIGO_CLIENT_URL}/api/auth/callback"  # yamllint disable-line rule:quoted-strings
      post-logout-redirect-uris:
        - "${TASKMIGO_CLIENT_URL}/"  # yamllint disable-line rule:quoted-strings
      scopes:
        - openid
        - profile
    require-proof-key: true
    require-authorization-consent: false
    token:
      access-token-time-to-live: PT5M
      refresh-token-time-to-live: PT8H
      reuse-refresh-tokens: false
