---
spring:
  config:
    import: classpath:application-database.yaml
  main:
    web-application-type: none
  flyway:
    enabled: true
    validate-migration-naming: true

taskmigo:
  audit:
    enabled: true

logging:
  structured:
    format:
      console: ecs
    ecs:
      service:
        name: taskmigo-migration
