---
spring:
  autoconfigure:
    exclude:
      - org.springframework.modulith.events.config.EventPublicationAutoConfiguration
  config:
    import: classpath:application-database.yaml
  main:
    web-application-type: none
  flyway:
    enabled: true
    validate-migration-naming: true
  modulith:
    events:
      externalization:
        mode: outbox

jobrunr:
  database:
    skip-create: true
  background-job-server:
    enabled: false

taskmigo:
  audit:
    enabled: true

logging:
  structured:
    format:
      console: ecs
    ecs:
      service:
        name: taskmigo-migration
