package io.taskmigo.web.adapter.in.http.api;

import static org.assertj.core.api.Assertions.assertThat;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import io.swagger.v3.core.util.Yaml;
import io.swagger.v3.oas.annotations.OpenAPIDefinition;
import io.swagger.v3.oas.annotations.enums.SecuritySchemeType;
import io.swagger.v3.oas.annotations.security.OAuthFlow;
import io.swagger.v3.oas.annotations.security.OAuthFlows;
import io.swagger.v3.oas.annotations.security.OAuthScope;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.security.SecurityScheme;
import io.swagger.v3.oas.models.info.Info;
import io.taskmigo.PostgresTestConfiguration;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Objects;
import org.junit.jupiter.api.Assumptions;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springdoc.core.models.GroupedOpenApi;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Import;
import org.springframework.web.client.RestClient;

@SpringBootTest(
    webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT,
    properties = {
        "springdoc.api-docs.enabled=true",
        "springdoc.api-docs.path=/api/docs/openapi.json",
        "springdoc.api-docs.version=openapi-3-1",
        "scalar.enabled=false",
        "taskmigo.oauth.signing-key-file=build/test-data/oauth-signing-key.pem",
        "taskmigo.oauth.signing-key-auto-create=true",
    }
)
@Import({ PostgresTestConfiguration.class, OpenApiGenerationIntegrationTest.OpenApiGenerationConfiguration.class })
class OpenApiGenerationIntegrationTest {

    private static final Path OPENAPI_DIRECTORY = Path.of("src/main/resources/static/api/docs");
    private static final Path OPENAPI_FILE = OPENAPI_DIRECTORY.resolve("openapi.yaml");

    @LocalServerPort
    int port;

    /**
     * Verifies that the manual OpenAPI generation task writes the current application contract
     * into the source-controlled YAML file.
     *
     * Given: the test is invoked by the generateOpenApi Gradle task.
     * Expect: openapi.yaml is replaced with the deterministic OpenAPI document generated by SpringDoc.
     */
    @Test
    @DisplayName("writes the committed OpenAPI YAML when manual generation is requested")
    void shouldWriteCommittedOpenApiYamlWhenManualGenerationIsRequested() throws IOException {
        // Arrange
        Assumptions.assumeTrue(Boolean.getBoolean("taskmigo.openapi.generate"));
        String generated = this.generatedOpenApiYaml();

        // Act
        Files.createDirectories(OPENAPI_DIRECTORY);
        Files.writeString(OPENAPI_FILE, generated, StandardCharsets.UTF_8);

        // Assert
        assertThat(Files.readString(OPENAPI_FILE, StandardCharsets.UTF_8)).isEqualTo(generated);
    }

    /**
     * Verifies that the source-controlled OpenAPI contract is synchronized with the current
     * controller and schema metadata without modifying the working tree.
     *
     * Given: the test is invoked by the verifyOpenApi Gradle task and openapi.yaml is committed.
     * Expect: regenerating the document in memory produces exactly the committed YAML bytes.
     */
    @Test
    @DisplayName("matches the committed OpenAPI YAML when staleness verification is requested")
    void shouldMatchCommittedOpenApiYamlWhenStalenessVerificationIsRequested() throws IOException {
        // Arrange
        Assumptions.assumeTrue(Boolean.getBoolean("taskmigo.openapi.verify"));
        String generated = this.generatedOpenApiYaml();

        // Act
        String committed = Files.readString(OPENAPI_FILE, StandardCharsets.UTF_8);

        // Assert
        assertThat(committed)
            .as("openapi.yaml is stale; run ./gradlew :apps:web:generateOpenApi and commit the result")
            .isEqualTo(generated);
    }

    private String generatedOpenApiYaml() {
        String openApi = Objects.requireNonNull(
            this.http().get().uri("/api/docs/openapi.json/v0").retrieve().body(String.class)
        );
        ObjectNode document = (ObjectNode) this.document(openApi);
        document.remove("servers");
        return "---\n" + Yaml.pretty(document);
    }

    private JsonNode document(String openApi) {
        try {
            return new ObjectMapper().readTree(openApi);
        } catch (Exception exception) {
            throw new AssertionError("OpenAPI document must be valid JSON", exception);
        }
    }

    private RestClient http() {
        return RestClient.builder()
            .baseUrl("http://localhost:" + this.port)
            .build();
    }

    @TestConfiguration(proxyBeanMethods = false)
    @OpenAPIDefinition(security = @SecurityRequirement(name = "taskmigoOAuth"))
    @SecurityScheme(
        name = "taskmigoOAuth",
        type = SecuritySchemeType.OAUTH2,
        flows = @OAuthFlows(
            authorizationCode = @OAuthFlow(
                authorizationUrl = "/oauth2/authorize",
                tokenUrl = "/oauth2/token",
                scopes = {
                    @OAuthScope(name = "openid", description = "OpenID Connect scope"),
                    @OAuthScope(name = "profile", description = "Access the user's profile information"),
                }
            )
        )
    )
    static class OpenApiGenerationConfiguration {

        @Bean
        GroupedOpenApi v0OpenApi() {
            return GroupedOpenApi.builder()
                .group("v0")
                .pathsToMatch("/api/v{version}/**")
                .addOpenApiCustomizer(openApi ->
                    openApi.info(new Info().title("Taskmigo API").version("v0").description("Taskmigo API"))
                )
                .build();
        }
    }
}
