name: Format Preview

on:
  push:
    branches:
      - improve/api-versioning

permissions:
  contents: read

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions/setup-node@v7.0.0
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - run: npm run format:fix
      - run: git diff --no-ext-diff --unified=100
